# config/routes.yaml

homepage:
    path: /
    controller: App\Controller\HomeController::homepage

app_home:
    path: /home
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_about:
    path: /about
    controller: App\Controller\HomeController::about

# Auto-discover routes from controller attributes
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
